### ISSUE TITLE
More than 2 perturbations per cell in training data

### ISSUE THREAD

**Issue by krejciadam** [snap-stanford/GEARS#11]
Hi! 
  I've been playing with the tool for a some time now and I ran into this: From the paper, I understood that the tool supports any number of perturbations in a single cell. Nevertheless, looking into the code, I found this line: 

https://github.com/snap-stanford/GEARS/blob/529b6c9ab84c27fd9696015583266abd49b3ddae/gears/data_utils.py#L58

which to my understanding means there can only be 1 or 2 perturbations in a single cell in the training dataset. I changed the line to: 

`adata.obs.loc[:, 'dose_val'] = adata.obs.condition.apply(lambda x: '+'.join('1'*len(x.split('+'))))`

to get correct dose strings for cells with more perturbations and everything seems to work. 

Is this a reasonable thing to do? And if so, what is the logic with adding `ctrl` to cells with fewer perturbations? What I mean is that in the notebook, you mention that only wild-type cells should have a single perturbation (`ctrl`) and cells with 1 perturbation should have the ctrl perturbation added (`gene1 + pertrubaton`) while cells with 2 perturbations do NOT have the ctrl perturbation added (`gene1 + gene2`). How should I extend the rule if I have, say, cells with between 0 and 6 perturbations? Thanks!

**Comment by yhr91** [comment]
Thanks for your question! You are correct that GEARS is designed to be able to handle an arbitrary number of perturbations per cell as long as they are all separated by a '+' operator. This information is parsed in the dataloader as shown in this function below which converts all applied perturbation to their corresponding indices.

https://github.com/snap-stanford/GEARS/blob/529b6c9ab84c27fd9696015583266abd49b3ddae/gears/pertdata.py#L286-L290

As for the convention of adding a `ctrl` only in the case of a single perturbation, this is due to a common naming convention seen in 2-gene combinatorial screen datasets. Sorry for the confusion. Any set of perturbations applied to a cell that is greater than 2 would not need the `ctrl` term added. So if perturbing genes `p, q, r and s`, you would simply input this as `p+q+r+s`, but if only perturbing p then it would be input as `p+ctrl`. We've never dealt with datasets containing perturbation sets of such high cardinality so would be interested to hear more about your experience applying GEARS to such a dataset.

As for the line of code that you link to, `adata.obs.loc[:, 'dose_val']` is a legacy field in the dataframe that we use when storing results from differential expression. Since GEARS was designed and tested mainly within the 1 and 2-gene setting we wrote the code to just differentiate between those two scenarios. Your framing is indeed more general and feel free to submit a pull request if you'd like us to update with your version. Having said that, in this case, the change in notation will not impact any of the results since it is only a change in the naming convention.

**Comment by krejciadam** [comment]
I see. Thank you, I'll proceed with that dataset and see how it goes.

FYI: The dataset I'm currently referring to was generated by superinfecting the cells with a small set of single guides, rather than by using a construct with pre-defined paris of guides like they did in _Norman et al_. To our experience, when one is using pre-defined constructs, the reasonable maximum is currently 3 guides per cell, and even that is rather challenging in the lab. On the other hand, one can get to many guides per cell by random superinfection, but the higher-order combinations are going to be rare. Obviously, even with small libraries an many cells, it is very unlikely to observe even 2 cells with the same combination of 6 guides. 
My intuitive approach with such datasets would be to pre-filter and only keep cells with combinations that are represented by a reasonably large set of cells, which effectively means that most of the cells I keep will anyway not carry more than 3 perturbations. But I also plan to experiment with including those cells with rare high-order combinations to see if there is any merit in doing so.

**Comment by yhr91** [comment]
Thanks for sharing, that sounds very interesting. You are right that often cells do get infected with more than 2 guides just by random chance, I'd be interested in hearing more about your results.
