### ISSUE TITLE
problems with dataloader between versions

### ISSUE THREAD

**Issue by AshirBorah** [snap-stanford/GEARS#22]
Hello!

Thank you for the great package. I have some code that relies on cell-gears=0.0.1. The latest version of cell-gears makes a lot of things much earlier including importing new datasets.

When I update to the current version, it seems like the dataloader only returns X with a single dimension  [batch_size*n_genes,1] while earlier it used to return a matrix of size [batch_size*n_genes,2]. The first axis are the expression flags while the second are the perturbation masks. Can you please help me figure out which part of the code changed so that I can figure out how to update to the latest version and still make things work?

Thank you!

**Comment by yhr91** [comment]
Hi, thanks for your question!

This change is because the previous version of GEARS (v0.0.1) would only predict the perturbation of genes that are also expressed, thus the perturbation flags could map directly to the indices of the genes that are expressed. In the final version of the paper we extended GEARS to predict perturbation of genes even if their expression is not measured. This involved several changes to how the dataloader is generated so I wouldn't recommend manually editing the repo to make it compatible with the previous dataloader. 

The simplest solution would be to just generate a new dataloader (v0.0.4). It should be pretty straightforward if you still have access to the original AnnData file and shouldn't impact any of your analyses down. If you want the same results as with the earlier version, I would also recommend setting `default_pert_graph=False` when initializing `PertData`

Let me know if this resolves your issue or if you still need some help!

**Comment by AshirBorah** [comment]
Thank you.

I ended up using some of the code from the older versions to create an additional vector and it worked. I really like the new version and it's added features.
