### ISSUE TITLE
Reproduce figure 2 b-g

### ISSUE THREAD

**Issue by subercui** [snap-stanford/GEARS#5]
Hi, could you provide code to reproduce figure 2b-g in your preprint? Or at least could tell how to rerun the analysis workflow?

![](https://www.biorxiv.org/content/biorxiv/early/2022/07/15/2022.07.12.499735/F2.large.jpg)

**Comment by kexinhuang12345** [comment]
Hi! Checkout https://github.com/snap-stanford/GEARS/blob/master/demo/model_tutorial.ipynb to reproduce the metrics (remember to set the epoch to at least 20). All the metrics will be automatically printed. If you have weight and bias, you can also flag that and it will log the metrics over there. 

For g, reproduce using this link: https://github.com/snap-stanford/GEARS/blob/master/demo/tutorial_plot_top20_DE.ipynb

You can also find more demos: https://github.com/snap-stanford/GEARS/tree/master/demo

**Comment by subercui** [comment]
Hi, thank you for the response. I don't think the links you provided can generate the figures. I checked your demos, they are mainly about basic usage of your model. 

It is difficult for one to map every detail setting in the paper to the code. For example, the `pert_data.prepare_split(split = 'simulation', seed = 1)` in the [moel_tutorial.ipynb](https://github.com/snap-stanford/GEARS/blob/master/demo/model_tutorial.ipynb), is it the proper split to generate the "1-gene perturbation" in 2b, and how about the splits in 2f?

And by saying "All the metrics will be automatically printed" do you mean the lines of test set scores in the notebook? Again, I think it is not straightforward which scores represent which in figure 2. Can you update the notebook and point them out?

Regarding these questions, I think providing a notebook to regenerate your figures could make this actually reproducible. Do you have any plan to do so?

**Comment by kexinhuang12345** [comment]
Sure! Just uploaded to the misc repo. Here are the links:

fig 2b adamson: https://github.com/yhr91/gears_misc/blob/main/paper/fig2b-adamson2016.ipynb
fig 2b dixit: https://github.com/yhr91/gears_misc/blob/main/paper/fig2b-dixit2016.ipynb
fig 2c and d: https://github.com/yhr91/gears_misc/blob/main/paper/fig2cd.ipynb
fig 2f: https://github.com/yhr91/gears_misc/blob/main/paper/fig2f.ipynb
fig 2g: https://github.com/yhr91/gears_misc/blob/main/paper/fig2g.ipynb

Do note that all of those notebooks use our weight and bias back end, which automatically fetch the logged results. 

Regarding the split question, yes, all figures use the 'simulation' split. This split automatically constructs 0/1/2 unseen perturbations. We use seed 1 to 5 and take the mean and standard deviation.

**Comment by subercui** [comment]
Thank you so much! This is extremely helpful

**Comment by zoepiran** [comment]
Hi, 
Following up on this, using the above, we were able to reproduce the performance results for Adamson and Norman however got different values for Dixit (of note, we tried increasing the number of epochs running with 15,20,40). We were wondering whether this dataset requires a different configuration? 
Thank you in advance!

**Comment by yhr91** [comment]
Thanks for your question. Were you using the pip installation of GEARS or clone from Github

**Comment by zoepiran** [comment]
clone from Github

**Comment by yhr91** [comment]
The current version of the repo on GitHub uses a different default Gene Ontology graph which is much larger than the one we used for the preprint with the goal of allowing a much broader set of unseen perturbations that can be predicted. However, the flip side of a larger graph is that for smaller datasets (like Dixit), it can affect the learnt node embeddings.

It's possible to regenerate the results in the preprint by using a custom list of genes for the dataloader parameter `essential genes` which determines the size of the Gene Ontology graph. This is set based on the input file `gene_path` that is provided to a `PertData` object for initialization. You can set this to be a list of perturbed genes in your dataset or a list of all expressed and perturbed genes in the dataset.

Alternately, you could use the pip installation and the default dataloader for the Dixit dataset. We plan to update the pip package soon to remove this inconsistency.

**Comment by zoepiran** [comment]
Great, thank you! we will try that. 
We turned to the cloned version as it had the option of "no_perturb" training for baseline comparison - is there an analogue in the pip version? 
(** we noticed that `GeneSimNetwork` can not handle a discrepancy between `node_map`  and `edge_list` in the construction of `edge_index_` )

**Comment by yhr91** [comment]
Sorry, I forgot to mention that if you use a custom gene list (`gene_path`) in the PertData dataloader then you also have to set `go_path` using a custom GO graph generated using that gene list. This is passed when initializing a GEARS model. So the steps are:

1. Create custom GO graph from a gene list using this [script](https://github.com/yhr91/gears_misc/blob/main/gears/make_GO.py)
2. Pass this new GO graph to the GEARS model object during initialization using the `go_path` argument
     `gears_model.model_initialize(hidden_size = 64, go_path='./data/go_essential_dixit.csv')`

As mentioned previously, we are working on automating this procedure for smaller datasets/custom graphs. We expect to update the repo soon.

**Comment by ekernf01** [comment]
I think there is still some detail left implicit so I want to explain my repro attempt and include some info people may find helpful. Maybe some of this context would fit will in `paper/README.md`?

### Intended first step is `fig2_train.py`

I tried running the fig2b adamson and dixit notebooks, but they fail with errors like "ValueError: Could not find project pert_gnn_simulation_adamson2016". I noticed the comment saying "Project is specified by <entity/project-name> please replace it with your project name here". I replaced with my own project name, but then there was no logged data. I concluded that **the intended first step is to train the models via `fig2_train.py`, not to run the notebooks**. All good so far -- I wanted to train the models up myself anyway, not just load evaluation results.

### Environment

I tried running `python3 fig2_train.py` but I needed to install the right set of packages. I used the attached file via `mamba env create --file  dependencies.yaml`. 

- Note: I have no GPU; this will install torch for CPU. For GPU, see [torch official install docs](https://pytorch.org/get-started/locally/).
- Note: this does not install GEARS itself. I assume `fig2_train.py`  is meant to pull in the copy of gears in this repo via `sys.path.append("../")`.
- [dependencies.yaml](https://github.com/snap-stanford/GEARS/files/11407414/dependencies.yaml.txt)

### Weaselling out of the GPU requirement 

I then ran `python3 fig2_train.py` and  `python3 fig2_train.py --device cpu`, but it seems GPU is currently a hard requirement. Wanting a GPU is reasonable but I checked to see how far I could weasel out of it. I modified lines 8 and 47 of `fig2_train.py` to allow users to pass in 'cpu' as the device, and I modified six lines in `utils.py` to avoid `+=` as per https://github.com/snap-stanford/GEARS/issues/9. This seemed to work -- I hit an issue, but not seemingly GPU-related. 

### Getting the GO graph

The next issue was two hardcoded paths in utils:

```python
df_jaccard = pd.read_csv('/dfs/user/kexinh/gears2/go_essential_gi.csv')
df_jaccard = pd.read_csv('/dfs/user/kexinh/gears2/go_essential_all.csv')
```
I changed these to `data/go_essential_norman.csv` since I have that file from following directions in `paper/README.md`. I notice those may not be actually used, depending on args passed to `get_similarity_network`. 

### Fin

This makes the training run (maybe with the wrong GO graph) and now it's running! I can report back once it finishes.

**Comment by yhr91** [comment]
Thanks for the detailed walkthrough @ekernf01. I'm glad that you were able to run the code to reproduce the results. We do not maintain the paper reproducibility repo as actively as this one but I'll make a note to update the README there.

**Comment by ekernf01** [comment]
I actually am still having trouble getting to figure 2b. It was necessary to modify `fig2_train.py` to accept the Adamson or Dixit data as input, and fix more no-CUDA issues, and then I did finish a training run on the Adamson data. But I can't get `Fig2b-Adamson2016.ipynb` to find the results. The relevant wandb output seems to be this:

```
wandb: Run data is saved locally in /home/ekernf01/Desktop/jhu/research/projects/perturbation_prediction/cell_type_knowledge_transfer/gears_misc/paper/wandb/run-20230508_212335-17rx8re0
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run gears_seed1
wandb: ⭐️ View project at https://wandb.ai/ekernf01/adamson
wandb: 🚀 View run at https://wandb.ai/ekernf01/adamson/runs/17rx8re0
```

But when I use either of the following lines to try to use the results to generate the figure, I get empty results or errors. 

```python
runs = api.runs("ekernf01/adamson/runs/17rx8re0") # ValueError: Could not find project adamson/gears_seed1
runs = api.runs("ekernf01/adamson")                        # This runs but the results dataframe is empty
```

I'm not familiar with wandb so is there an easy fix that I am missing regarding the path it expects to see? 

Thank you! I really appreciate your attention!

**Comment by yhr91** [comment]
Are you able to see the results from training the model on the wandb page? Can you make your project public?

**Comment by yhr91** [comment]
Thanks for sharing. It looks like your results were correctly tracked on the wandb and I'm able to access them through the notebook. The empty results dataframe is because the name for your models in wandb `gears_seed_1` is different from the name that the plotting notebook expects `PertNet_API_Seed_1`. You can correct that retrospectively from the wandb interface by simply right-clicking the run which completed.

Then, there are also several runs on your wandb that did not complete, and those will likely throw errors for some of the downstream functions. Finally, you don't have any runs from the other baselines, so you will likely have to manually comment those sections out. 

We'll make a note to update this notebook but it's hard to run these plotting notebooks with no edits at all since there tend to always be a few minor variations in everyone's implementation. If it's just the MSE value you're interested in, then you just need to run the first cell in the notebook and print `summary_list[model_index]['test_mse_top20_de_non_dropout']`

**Comment by ekernf01** [comment]
Thank you -- I got the top-20 MSE and it looks just like fig 2b, 0.447. I really appreciate your help.

**Comment by ekernf01** [comment]
I am actually still noticing problems -- the analysis I just described is based on very few perturbations, maybe because the GO graph used is for the Norman data. I tried to follow your earlier comments by using `make_GO.py` to make a different GO graph, but it throws an error looking for another missing file related to the Dixit data. I just don't know where to get all the accessory data and how to arrange it. I know you have said the figure reproduction repo is not as actively maintained, and I can understand that. Let me know if you would rather leave this issue closed or continue to pursue it.

**Comment by yhr91** [comment]
I'll get back to you on this by the end of the week

**Comment by yhr91** [comment]
Ok, I've updated the gears pip package. You should be able to reproduce all the results in the preprint by running this [notebook](https://github.com/yhr91/gears_misc/blob/main/paper/reproduce_preprint_results.ipynb)

Note that this notebook requires the latest pip version of gears ([0.0.4](https://pypi.org/project/cell-gears/0.0.4/)) and does not use the local implementation of gears in that repository.

The code is mostly the same except now you only need to set a single flag (`default_pert_graph`) when setting up the `PertData` dataloader. When `default_pert_graph=True`, it uses the default large perturbation graph. When `default_pert_graph=False`, it uses a smaller graph based on the genes and perturbations used in each dataset (the procedure followed in the preprint).

**Comment by yhr91** [comment]
Code from the notebook above was run as-is over 15 epochs to reproduce Fig 2b. Results can also be obtained directly from the public Wandb links ([Dixit](https://wandb.ai/yroohani/dixit?workspace=user-yroohani), [Adamson](https://wandb.ai/yroohani/adamson?workspace=user-yroohani))

**Comment by Maojie6509** [comment]
Hi, I still encountered some problems when I tried to reproduce fig2. I hope I can get some help  Following the guide in  To recreate Fig 2:

Download and unzip preprocessed Norman2019 dataloader for GEARS [here](https://dataverse.harvard.edu/api/access/datafile/6894431)
Move the uncompressed norman2019.tar.gz folder to ./data. It should contain the subdirectory data_pyg
Move essential_norman.pkl and go_essential_norman.csv to ./data
So ./data should contain essential_norman.pkl, go_essential_norman.csv and norman2019/data_pyg/
Run fig2_train.py to train the model

**Comment by Maojie6509** [comment]
Hello, I still encountered some problems when I tried to reproduce fig2. I hope I can get some help 
I follow the steps under the link ([GEARS_misc/paper at main · yhr91/GEARS_misc (github.com)](https://github.com/yhr91/GEARS_misc/tree/main/paper)) to recreate Fig 2. Now,   the ./data contain essential_norman.pkl, go_essential_norman.csv and norman2019/data_pyg/ . 
![image](https://github.com/snap-stanford/GEARS/assets/9159535/ca929f50-9b1c-4a0a-a31e-09175ebafe69)

When I run  python fig2_train.py to train the model ,get some error 
![image](https://github.com/snap-stanford/GEARS/assets/9159535/fd1fad2f-f237-4edf-a139-283d2ffa754b)

**Comment by yhr91** [comment]
Sorry for the confusion, the latest version of GEARS has changed the dataloader input format. It doesn't explicitly need the gene list.

I've updated [that script](https://github.com/yhr91/GEARS_misc/blob/main/paper/fig2_train.py) to work with GEARS v0.1.1. It should work now without any errors.
