### ISSUE TITLE
Questions about reproduction of Figure2cd

### ISSUE THREAD

**Issue by zhoummmin** [snap-stanford/GEARS#51]
Hi,
Thank you for publishing such an excellent paper!  I'm trying to reproduce the results of Figure2c and 2d. In the GEARS_misc/paper/Fig2cd.ipynb, I noticed that the color_pal is directly input. Could you please provide any guidance on how to reproduce these data and how could I get the perturbation results for all genes？
Forgive me for my inexperience, thank you and have a nice day!
<img width="698" alt="image" src="https://github.com/snap-stanford/GEARS/assets/135788068/5b715db2-8267-4f8c-a6a6-c943e7bcf6ab">

**Comment by zhoummmin** [comment]
I apologize for the inconvenience once again. Could you kindly verify whether the data location in this notebook is still accurate? I seem to have encountered some file non-existence problems during operation. May I inquire if it would be possible to communicate with you via email? I eagerly await your response. Thank you very much for your consideration!
<img width="674" alt="image" src="https://github.com/snap-stanford/GEARS/assets/135788068/9384c2ea-91a6-406a-a1b1-a1cdf9ac4964">

**Comment by yhr91** [comment]
Thanks for your question

color_pal in `GEARS_misc/paper/Fig2cd.ipynb` just refers to the color palette for the figures and is manually set. It does not refer to the experimental results.

To reproduce the results for GEARS on your own, you can follow this [notebook](https://github.com/yhr91/GEARS_misc/blob/main/paper/reproduce_preprint_results.ipynb) 

To plot the results you can point it at your own wandb account where the results from your run would be saved. Otherwise the wandb project linked in the notebook could also be used for the Norman dataset but not for the other two. However, it shouldn't take long to manually regenerate the results for `adamson2016` and `dixit2016` if you follow the notebook
